SUPTITLE_FONT_SIZE = 24
TITLE_FONT_SIZE = 22
AXIS_FONT_SIZE = 14
AXIS_TICK_FONT_SIZE = 12
FIG_DIM_X = 10
FIG_DIM_Y = 8

QUOTIENT_LOWER_LIM = -0.1
QUOTIENT_UPPER_LIM = 0.8


SCATTER_MARKER_SIZE_SMALL = 1.25
SCATTER_MARKER_SIZE_LARGE = 8
SCATTER_MARKER_DOT = "."
SCATTER_MARKER_CIRCLE = "o"

CLASSIFICATION_PLOT_RES = 500
HISTOGRAM_RES = 256