FONT_SIZE = 14
FIG_DIM_X = 12
FIG_DIM_Y = 9

QUOTIENT_LOWER_LIM = -0.1
QUOTIENT_UPPER_LIM = 0.8


SCATTER_MARKER_SIZE_SMALL = 1.25
SCATTER_MARKER_SIZE_LARGE = 8
SCATTER_MARKER_DOT = "."
SCATTER_MARKER_CIRCLE = "o"
